package com.stutteranalyzer.crash;

import com.stutteranalyzer.StutterAnalyzerFabric;
import com.stutteranalyzer.pattern.KnownPatternDetector;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

public class CrashHintInjector {

    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd", Locale.ROOT);

    public static void writeHint(Path crashFile, List<KnownPatternDetector.PatternMatch> matches) {
        if (matches.isEmpty()) return;
        KnownPatternDetector.PatternMatch best = matches.get(0);

        String date = FMT.format(LocalDateTime.now());
        String hintFileName = "crash-" + date + "-stutter-analyzer-hints.md";

        try {
            Path hintDir = crashFile.getParent() != null ? crashFile.getParent() : crashFile;
            Path hintFile = hintDir.resolve(hintFileName);

            try (FileWriter fw = new FileWriter(hintFile.toFile(), true)) {
                fw.write("# Stutter Analyzer Hints\n\n");
                fw.write("Related crash: `" + crashFile.getFileName() + "`\n\n");
                fw.write("## Known Pattern Context\n");
                fw.write("Pattern: `" + best.patternId + "`\n");
                fw.write("Confidence: " + best.confidencePct() + "%\n\n");
                fw.write("## Evidence\n");
                fw.write(best.reason + "\n\n");
                fw.write("## Safe Automatic Workaround\n");
                fw.write(safeWorkaround(best.patternId) + "\n\n");
                fw.write("## Recommended Action\n");
                fw.write(recommendation(best.patternId) + "\n\n");
                fw.write("---\n");
                fw.write("*This file was generated by StutterAnalyzer. World data was not modified.*\n");
            }

            LatestLogHintWriter.appendHint(best.patternId, best.confidencePct());

        } catch (IOException e) {
            StutterAnalyzerFabric.LOGGER.error("[StutterAnalyzer] CrashHintInjector failed: {}", e.getMessage());
        }
    }

    private static String safeWorkaround(String patternId) {
        return switch (patternId) {
            case "RUBIDIUM_LAVA_FLUID_RENDER_CRASH" ->
                "Emergency Guard can skip the unsafe lava fluid render operation (enable emergency_mode in config).";
            default -> "none - warn/report only for this pattern.";
        };
    }

    private static String recommendation(String patternId) {
        return switch (patternId) {
            case "RUBIDIUM_LAVA_FLUID_RENDER_CRASH" ->
                "- Replace or update Rubidium (try Embeddium/Xenon if compatible).\n" +
                "- Test with shaders disabled.\n" +
                "- Attach this crash report and latest.log to a GitHub issue.";
            case "C2ME_CORRUPTED_CHUNK_CONTEXT" ->
                "- Back up the world before changing C2ME recovery settings.\n" +
                "- Try without C2ME to isolate the issue.";
            case "IRIS_OCULUS_SHADER_PIPELINE_CONTEXT" ->
                "- Test with shaders disabled.\n" +
                "- Update Iris/Oculus and Sodium/Embeddium together.\n" +
                "- Attach crash report and latest.log.";
            default ->
                "- Enable debug mode and reproduce.\n" +
                "- Export report and submit via /sa submit.";
        };
    }
}
