package com.stutteranalyzer.guard;

import java.time.Instant;

public class EmergencyGuardReport {

    public final String guardId;
    public final String patternId;
    public final EmergencyGuardResult.Outcome outcome;
    public final String action;
    public final double confidence;
    public final Instant timestamp = Instant.now();

    public EmergencyGuardReport(String guardId, EmergencyGuardResult result) {
        this.guardId    = guardId;
        this.patternId  = result.patternId;
        this.outcome    = result.outcome;
        this.action     = result.action;
        this.confidence = result.confidence;
    }

    public String toMarkdown() {
        return "# Emergency Guard Report\n\n" +
            "## Guard\n" + patternId + "\n\n" +
            "## Outcome\n" + outcome.name() + "\n\n" +
            "## Action taken\n" + (action.isEmpty() ? "none (warn only)" : action) + "\n\n" +
            "## Safety\n" +
            "World data was not modified.\n" +
            "Server logic was not modified.\n" +
            "Only client-side rendering was affected (if applicable).\n\n" +
            "## Confidence\n" + (int)(confidence * 100) + "%\n\n" +
            "## Timestamp\n" + timestamp + "\n\n" +
            "*Generated by StutterAnalyzer. No mod was disabled automatically.*\n";
    }
}
